- hosts: webserver
  become: yes
  tasks:
    - name: Updating the server
      shell: |
        apt-get update -y
        apt-get upgrade -y
    - name: Install Node.js and NPM
      shell: |
        apt-get install curl -y
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        apt-get install -y nodejs
    - name: Nodejs version
      shell: |
        node -v
        npm -v
    - name: Clone the MERN application repository
      git:
        repo: 'https://github.com/UnpredictablePrashant/TravelMemory.git'
        path: /home/ubuntu
    - name: Install dependencies
      shell: |
        cd /home/ubuntu
        npm i
